#!/bin/bash

mkdir ./ft_out
mkdir ./ft_seq
while read line;
do
ext="Aligned.sortedByCoord.out.bam"
file_out=$line$ext
featureCounts -T 48 -t exon -g gene_id -p -s 2 -a /home/fangao/refdata-cellranger-hg19-1.2.0/genes/genes.gtf -o ./ft_out/ft_$line.txt $file_out
done < sample_ID.txt

#-s 1 stranded; -s 2 reverse stranded;

while read line;
do
cat ./ft_out/ft_$line.txt | awk '{if($1!="#" && $1!="Geneid")print $1"\t"$7}' > ./ft_seq/ftcounts_$line.txt
done < sample_ID.txt

